
name: debug
root: /home/lijj/domain_seg/code/pixmatch-master/pixmatch-master
data_leinao: /data/lijj
pretrain_model_root: /data/lijj/pretrain_model/pixmatch/
train: True
seed: 42
wandb: False

data:

  num_classes: 19

  source:
    dataset: 'gta5'
    kwargs:
      root: ${data_leinao}/GTA5
      list_path: ${root}/datasets/gta5_list
      base_size: [1280, 720]
      crop_size: [1280, 720]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False

  target:
    dataset: 'cityscapes'
    kwargs:
      root: ${data_leinao}/Cityscapes
      list_path: ${root}/datasets/city_list
      base_size: [1280, 640]
      crop_size: [1280, 640]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False
      class_13: False

  loader:
    kwargs:
      batch_size: 1
      num_workers: 4
      pin_memory: True
  target_loader:
    kwargs:
      batch_size: 2
      num_workers: 4
      pin_memory: True      
  source_loader:
    kwargs:
      batch_size: 2
      num_workers: 4
      pin_memory: True 
      
  source_val_iterations: 100

model:
  backbone: deeplabv2_multi
  imagenet_pretrained: ${pretrain_model_root}/DeepLab_resnet_pretrained_init-f81d91e8.pth
  #checkpoint: "/data/lijj/pretrain_model/pixmatch/synthia_source.pth"#
  checkpoint: "${pretrain_model_root}/GTA5_source.pth"#"/data/lijj/pixmatch_output/2022-01-22/22-03-19/best.pth"
  resume_from_checkpoint: True
  resume_from_checkpoint_finetune: False

opt:
  kind: "SGD"
  momentum: 0.9
  weight_decay: 5e-4
  lr: 2.5e-4
  iterations: 250000
  poly_power: 0.9

# For auxiliary mode output
aux: True
lam_aux: 0.1

# Exponential weighted average of model parameters
ema_decay: 0.999

# Perturbations
pseudolabel_threshold: 0.0
lam_aug: 0.0
lam_fourier: 0.0
lam_cutmix: 0.0
NCE_weight: 0.01
mix_weight: 0.1
Tmax: 0.95

# Fourier
source_fourier: False
fourier_beta: 0.01
