# @package _global_
defaults:
  - gta5
  - _self_

data:

  num_classes: 16

  source:
    dataset: 'synthia'
    kwargs:
      #root: ${root}/datasets/SYNTHIA/RAND_CITYSCAPES
      root: ${data_leinao}/synthia
      list_path: ${root}/datasets/synthia_list
      class_16: True

  target:
    kwargs:
      class_16: True

model:
  backbone: deeplabv2_multi
  #checkpoint: null
NCE_weight: 0.008